"""
Django settings for fcz project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f33y7!es8+35f2zfpx+rse@!aprsr=aa3e#vt&j%tas0(%s&6i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fcz',
    'fcz_plane',
    'i18n'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fcz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fcz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fcz',
        # 'NAME': 'boss',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        # 'HOST': '120.78.202.21',
        'PORT': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

ALL_HOT_AIRPORTS = \
    {'成都双流': 'CTU', '上海虹桥': 'SHA', '上海浦东': 'PVG', '北京1': 'PEK', '北京2': 'NAY', '北京首都': 'PEK', '北京南苑': 'NAY', '香港赤鱲角': 'HKG',
     '广州白云': 'CAN', '杭州萧山': 'HGH', '厦门高崎': 'XMN', '南京禄口': 'NKG', '南宁吴圩': 'NNG', '澳门': 'MFM',
     '青岛流亭': 'TAO', '台北1': 'TPE', '台北2': 'TSA', '台北松山': 'TSA', '台北桃园': 'TPE', '福州长乐': 'FOC',
     '天津滨海': 'TSN', '深圳宝安': 'SZX', '大连': 'DLC', '沈阳桃仙': 'SHE', '昆明长水': 'KMG', '武汉天河': 'WUH',
     '宁波栎社': 'NGB', '无锡硕放': 'WUX', '泉州晋江': 'JJN', '重庆江北': 'CKG', '三亚凤凰': 'SYX', '西安咸阳': 'XIY'}
